# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "CamerasRJ"
license = "MIT"
licenselink = "https://www.camerasrj.com.br/themes/camerasrj/LICENSE"
description = "Custom theme for Cameras da CET RJ"
homepage = "https://www.camerasrj.com.br/"
tags = ["cameras", "traffic", "city", "bootstrap"]
features = ["responsive", "ads", "analytics"]
min_version = "0.111.0"

[author]
  name = "Monique Oliveira"
  homepage = "https://monique.dev/"
